/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.3
// source: proto/transaction.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_transaction_pb from './transaction_pb'; // proto import: "proto/transaction.proto"


export class TransactionServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateTransaction = new grpcWeb.MethodDescriptor(
    '/proto.TransactionService/CreateTransaction',
    grpcWeb.MethodType.UNARY,
    proto_transaction_pb.CreateTxnRequest,
    proto_transaction_pb.TransactionUpdateResponse,
    (request: proto_transaction_pb.CreateTxnRequest) => {
      return request.serializeBinary();
    },
    proto_transaction_pb.TransactionUpdateResponse.deserializeBinary
  );

  createTransaction(
    request: proto_transaction_pb.CreateTxnRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_transaction_pb.TransactionUpdateResponse>;

  createTransaction(
    request: proto_transaction_pb.CreateTxnRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.TransactionUpdateResponse) => void): grpcWeb.ClientReadableStream<proto_transaction_pb.TransactionUpdateResponse>;

  createTransaction(
    request: proto_transaction_pb.CreateTxnRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.TransactionUpdateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.TransactionService/CreateTransaction',
        request,
        metadata || {},
        this.methodDescriptorCreateTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.TransactionService/CreateTransaction',
    request,
    metadata || {},
    this.methodDescriptorCreateTransaction);
  }

  methodDescriptorUpdateStatus = new grpcWeb.MethodDescriptor(
    '/proto.TransactionService/UpdateStatus',
    grpcWeb.MethodType.UNARY,
    proto_transaction_pb.UpdateStatusRequest,
    proto_transaction_pb.TransactionUpdateResponse,
    (request: proto_transaction_pb.UpdateStatusRequest) => {
      return request.serializeBinary();
    },
    proto_transaction_pb.TransactionUpdateResponse.deserializeBinary
  );

  updateStatus(
    request: proto_transaction_pb.UpdateStatusRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_transaction_pb.TransactionUpdateResponse>;

  updateStatus(
    request: proto_transaction_pb.UpdateStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.TransactionUpdateResponse) => void): grpcWeb.ClientReadableStream<proto_transaction_pb.TransactionUpdateResponse>;

  updateStatus(
    request: proto_transaction_pb.UpdateStatusRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.TransactionUpdateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.TransactionService/UpdateStatus',
        request,
        metadata || {},
        this.methodDescriptorUpdateStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.TransactionService/UpdateStatus',
    request,
    metadata || {},
    this.methodDescriptorUpdateStatus);
  }

  methodDescriptorGetTransaction = new grpcWeb.MethodDescriptor(
    '/proto.TransactionService/GetTransaction',
    grpcWeb.MethodType.UNARY,
    proto_transaction_pb.GetTxnRequest,
    proto_transaction_pb.Transaction,
    (request: proto_transaction_pb.GetTxnRequest) => {
      return request.serializeBinary();
    },
    proto_transaction_pb.Transaction.deserializeBinary
  );

  getTransaction(
    request: proto_transaction_pb.GetTxnRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_transaction_pb.Transaction>;

  getTransaction(
    request: proto_transaction_pb.GetTxnRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.Transaction) => void): grpcWeb.ClientReadableStream<proto_transaction_pb.Transaction>;

  getTransaction(
    request: proto_transaction_pb.GetTxnRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.Transaction) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.TransactionService/GetTransaction',
        request,
        metadata || {},
        this.methodDescriptorGetTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.TransactionService/GetTransaction',
    request,
    metadata || {},
    this.methodDescriptorGetTransaction);
  }

  methodDescriptorListTransactions = new grpcWeb.MethodDescriptor(
    '/proto.TransactionService/ListTransactions',
    grpcWeb.MethodType.UNARY,
    proto_transaction_pb.TxnFilter,
    proto_transaction_pb.TxnList1,
    (request: proto_transaction_pb.TxnFilter) => {
      return request.serializeBinary();
    },
    proto_transaction_pb.TxnList1.deserializeBinary
  );

  listTransactions(
    request: proto_transaction_pb.TxnFilter,
    metadata?: grpcWeb.Metadata | null): Promise<proto_transaction_pb.TxnList1>;

  listTransactions(
    request: proto_transaction_pb.TxnFilter,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.TxnList1) => void): grpcWeb.ClientReadableStream<proto_transaction_pb.TxnList1>;

  listTransactions(
    request: proto_transaction_pb.TxnFilter,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_transaction_pb.TxnList1) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.TransactionService/ListTransactions',
        request,
        metadata || {},
        this.methodDescriptorListTransactions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.TransactionService/ListTransactions',
    request,
    metadata || {},
    this.methodDescriptorListTransactions);
  }

}

