apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
      - name: ledger-service
        image: ledger-service:latest
        imagePullPolicy: Never
        ports:
        - name: grpc
          containerPort: 8080
        env:
          - name: DB_HOST
            value: "postgres"          # Use the PostgreSQL service name
          - name: DB_PORT
            value: "5432"               # Port exposed in PostgreSQL service
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB          
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  selector:
    app: ledger-service