apiVersion: v1
kind: Service
metadata:
  name: benchmark-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9091"       # Port where metrics are exposed
    prometheus.io/path: "/metrics"   # Path for metrics
spec:
  type: NodePort                      # Expose the service outside the cluster
  ports:
    - name: metrics
      port: 9091                      # Internal port on the service
      targetPort: 9091                # Port on the pod where the app exposes metrics
  selector:
    app: benchmark-service
