apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
      annotations:
        prometheus.io/scrape: "true"      
        prometheus.io/port: "8080"        
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: card-service
        image: card-service:latest
        imagePullPolicy: Never
        ports:
        - name: grpc
          containerPort: 8080
        env:
          - name: DB_HOST
            value: "postgres"          # Use the PostgreSQL service name
          - name: DB_PORT
            value: "5432"               # Port exposed in PostgreSQL service
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: card-service
  labels:
    app: card-service
  annotations:
    prometheus.io/scrape: "true"        
    prometheus.io/port: "9091"          
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 8080
    targetPort: grpc
  - name: metrics
    port: 9091
    targetPort: 9091
  selector:
    app: card-service