apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - source_labels: [__meta_kubernetes_node_name]
            target_label: node
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']
      - job_name: 'card-service'
        static_configs:
          - targets: ['card-service.default.svc.cluster.local:9091']      
        kubernetes_sd_configs:
          - role: service
            namespaces: 
              names:
                - default
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"  # Only keep services with the scrape annotation
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
            target_label: __param_port
          - source_labels: [__param_port]
            target_label: port
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: app
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            target_label: __param_path
            regex: (.*)
          - source_labels: [__param_path]
            target_label: path
        metric_relabel_configs:
          - source_labels: [__name__]
            target_label: _name_
