apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dotnetservice-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnetservice  # This is the name of your deployment
  minReplicas: 1  # Minimum number of pods to run
  maxReplicas: 10  # Maximum number of pods to scale to
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Scale up/down when CPU utilization is above 50%
