apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetservice
  labels:
    app: dotnetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetservice
  template:
    metadata:
      labels:
        app: dotnetservice
    spec:
      containers:
        - name: dotnetservice
          image: dotnetservice:latest 
          imagePullPolicy: Never
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          ports:
          - containerPort: 5000
            protocol: TCP
          command: ["dotnet", "dotnetservice.dll"]
          resources:
           requests:
            cpu: "250m"
            memory: "512Mi"
           limits:
            cpu: "500m"
            memory: "1Gi"
           
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetservice
spec:
  selector:
    app: dotnetservice
  ports:
    - protocol: TCP
      port: 5001 
      targetPort: 5001
  type: ClusterIP  
