// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/spike.proto

package spike

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpikeService_TriggerSpike_FullMethodName = "/spike.SpikeService/TriggerSpike"
)

// SpikeServiceClient is the client API for SpikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpikeServiceClient interface {
	TriggerSpike(ctx context.Context, in *SpikeRequest, opts ...grpc.CallOption) (*SpikeResponse, error)
}

type spikeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpikeServiceClient(cc grpc.ClientConnInterface) SpikeServiceClient {
	return &spikeServiceClient{cc}
}

func (c *spikeServiceClient) TriggerSpike(ctx context.Context, in *SpikeRequest, opts ...grpc.CallOption) (*SpikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpikeResponse)
	err := c.cc.Invoke(ctx, SpikeService_TriggerSpike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpikeServiceServer is the server API for SpikeService service.
// All implementations must embed UnimplementedSpikeServiceServer
// for forward compatibility.
type SpikeServiceServer interface {
	TriggerSpike(context.Context, *SpikeRequest) (*SpikeResponse, error)
	mustEmbedUnimplementedSpikeServiceServer()
}

// UnimplementedSpikeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpikeServiceServer struct{}

func (UnimplementedSpikeServiceServer) TriggerSpike(context.Context, *SpikeRequest) (*SpikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerSpike not implemented")
}
func (UnimplementedSpikeServiceServer) mustEmbedUnimplementedSpikeServiceServer() {}
func (UnimplementedSpikeServiceServer) testEmbeddedByValue()                      {}

// UnsafeSpikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpikeServiceServer will
// result in compilation errors.
type UnsafeSpikeServiceServer interface {
	mustEmbedUnimplementedSpikeServiceServer()
}

func RegisterSpikeServiceServer(s grpc.ServiceRegistrar, srv SpikeServiceServer) {
	// If the following call pancis, it indicates UnimplementedSpikeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpikeService_ServiceDesc, srv)
}

func _SpikeService_TriggerSpike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpikeServiceServer).TriggerSpike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpikeService_TriggerSpike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpikeServiceServer).TriggerSpike(ctx, req.(*SpikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpikeService_ServiceDesc is the grpc.ServiceDesc for SpikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spike.SpikeService",
	HandlerType: (*SpikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerSpike",
			Handler:    _SpikeService_TriggerSpike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spike.proto",
}
